export const ActionTypes = {
    FETCH_PRODUCTS: "FETCH_PRODUCTS",
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_ SELECTED_PRODUCT",
    GET_CART: "GET_CART",
    REMOVE_CART: "REMOVE_CART" 
}